name: Build, Test, and Deliver Client

on:
  pull_request:
  push:
    branches:
      - main
      - release/[0-9]+.[0-9]+.[0-9]+
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: './lib/package-lock.json'
      - run: npm ci
      - run: npm test
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: lib/coverage/
      - run: npm audit
      - run: npm run license-check
      - run: npm run lint
      - run: npm pack
      - uses: actions/upload-artifact@v2
        with:
          name: opentdf-client-lib
          path: ./lib/opentdf-client-*.tgz

  cli:
    needs:
      - lib
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: './cli/package-lock.json'
      - uses: actions/download-artifact@v2
        with:
          name: opentdf-client-lib
      - run: npm uninstall @opentdf/client && npm ci && npm i ../opentdf-client-*.tgz
      - run: npm test
      - run: npm audit
      - run: npm run license-check
      - run: npm run lint
      - run: npm pack
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - run: bats bin/opentdf.bats

  sample-web-app:
    needs:
      - lib
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sample-web-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: './sample-web-app/package-lock.json'
      - uses: actions/download-artifact@v2
        with:
          name: opentdf-client-lib
      - run: npm uninstall @opentdf/client && npm ci && npm i ../opentdf-client-*.tgz
      - run: npm install
      - run: npm test
      - run: npm audit
      - run: npm run license-check
      - run: npm run lint
      - run: npm pack

  scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/workflows
    steps:
      - uses: actions/checkout@v2
      - uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - name: 🦇🦇🦇🦇🦇🦇
        run: docker run --rm -v "$PWD:/mnt" --workdir "/mnt" bats/bats:1.5.0 *.bats
      - name: 🦪 ✔ 🧼🧼🧼
        run: >-
          docker run --rm -v "$PWD:/mnt" --workdir "/mnt" "koalaman/shellcheck:v0.8.0"
          --color=always *.sh

  format:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: './lib/package-lock.json'
      - run: make format
      - name: ignore package-lock changes
        run: git checkout -- {cli,sample-web-app}/package-lock.json
      - name: Commit changes
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |-
            🤖 🎨 Autoformat
            
      - name: Suggest user signoff
        if: steps.auto-commit.outputs.changes_detected == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `If these changes look good, signoff on them with:
            \`\`\`
            git pull && git commit --amend --signoff && git push --force-with-lease origin
            \`\`\`

            If they aren't any good, please remove them with:
            \`\`\`
            git pull && git reset --hard HEAD~1 && git push --force-with-lease origin
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });

  deliver-ghp:
    runs-on: ubuntu-latest
    needs: [lib, cli, sample-web-app, scripts]
    # To publish from a release or feature branch, remove the ref == condition below
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com
      - run: |-
          if [[ ${{ github.ref }} = refs/heads/release/* ]]; then
            scripts/check-version-is.sh "${GITHUB_REF##*release/}"
          elif [[ ${{ github.ref }} = refs/tags/v* ]]; then
            scripts/check-version-is.sh "${GITHUB_REF_NAME#v}"
          else
            scripts/check-version-is.sh
          fi
      - run: make test
      - run:
          .github/workflows/publish-to.sh $(.github/workflows/gh-semver.sh)
          $(.github/workflows/guess-dist-tag.sh)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: trigger xtest
        run: |
          curl -XPOST -u "virtru-cloudnative:${{secrets.PERSONAL_ACCESS_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" "https://api.github.com/repos/opentdf/backend/dispatches" --data '{"event_type": "xtest", "client_payload": {"version":"'$(BUILD_META="" .github/workflows/gh-semver.sh)'"}}'

  deliver-npmjs:
    runs-on: ubuntu-latest
    environment: npmjs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: deliver-ghp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |-
          if [[ ${{ github.ref }} = refs/heads/release/* ]]; then
            scripts/check-version-is.sh "${GITHUB_REF##*release/}"
          elif [[ ${{ github.ref }} = refs/tags/v* ]]; then
            scripts/check-version-is.sh "${GITHUB_REF_NAME#v}"
          else
            scripts/check-version-is.sh
          fi
      - run: make test
      - run:
          .github/workflows/publish-to.sh $(.github/workflows/gh-semver.sh)
          $(.github/workflows/guess-dist-tag.sh)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
