name: Check Version

on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |-
          if ! scripts/check-version-is.sh; then
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} scripts/gh-check.sh "Check Version" "failure"
          else
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} scripts/gh-check.sh "Check Version" "success"
          fi
