name: Integration Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: make test
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: lib/coverage/
