name: Integration Test

on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |-
          if ! scripts/check-version-is.sh; then
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} scripts/gh-check.sh "Check Version" "failure"
          else
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} scripts/gh-check.sh "Check Version" "success"
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: make test
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: lib/coverage/
