name: Integration Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: scripts/check-version-is.sh
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: make all
      - run: make test
      - run: make lint
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: lib/coverage/
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - run: bats cli/bin/opentdf.bats
