name: just trigger xtest

on:
  push:
jobs:
  deliver-ghp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com
      - run: .github/workflows/gh-semver.sh
      - name: trigger xtest
        run: >-
          curl -XPOST -u "virtru-cloudnative:${{secrets.PERSONAL_ACCESS_TOKEN}}"
              -H "Accept: application/vnd.github.everest-preview+json"
              -H "Content-Type: application/json"
              https://api.github.com/repos/opentdf/backend
              --data '{"event_type": "xtest", "client_payload": "{\"version\": \"'$(.github/workflows/gh-semver.sh)'\"}"}'
