name: Large file test

on:
  pull_request:
  push:
    branches:
      - main
      - feature/large-okish
  schedule:
    - cron: '0 4 * * 2,4'
jobs:
  large-file-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/workflows/roundtrip
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './web-app/package-lock.json'
      - run: make all && make test
      - name: run platform
        uses: opentdf/platform/test/start-up-with-containers@main
      - run: docker compose up -d --wait --wait-timeout 240
      - env:
          PLAYWRIGHT_TESTS_TO_RUN: huge roundtrip
        run: |-
          ./wait-and-test.sh platform
