name: Merge Request Testing

on: pull_request

jobs:
  lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: './lib/package-lock.json'
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm pack
      - uses: actions/upload-artifact@v2
        with:
          name: opentdf-client-lib
          path: ./lib/opentdf-client-*.tgz
          retention-days: 1

  cli:
    needs:
      - lib
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: './cli/package-lock.json'
      - uses: actions/download-artifact@v2
        with:
          name: opentdf-client-lib
      - run: npm uninstall @opentdf/client && npm ci && npm i ../opentdf-client-*.tgz
      - run: npm test
      - run: npm run lint
      - run: npm pack

  sample-web-app:
    needs:
      - lib
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sample-web-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: './sample-web-app/package-lock.json'
      - uses: actions/download-artifact@v2
        with:
          name: opentdf-client-lib
      - run: npm uninstall @opentdf/client && npm ci && npm i ../opentdf-client-*.tgz
      - run: npm install
      - run: npm test
      - run: npm run lint
      - run: npm pack
