name: Merge Request Testing

on: pull_request

jobs:
  lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
      - run: npm run lint

  cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/checkout@v2
      - run: make ci
        working-directory: ./
      - run: npm test
      - run: npm run lint

  sample-web-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sample-web-app
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/checkout@v2
      - run: make ci
        working-directory: ./
      - run: npm install
      - run: npm test
      - run: npm run lint
