name: NPM Deploy

on:
  push:
    branches:
      - main
      - release/[0-9]+.[0-9]+.[0-9]+
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: npmjs

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |-
          if [[ $GITHUB_REF = *release/* ]]; then
            scripts/check-version-is.sh "${GITHUB_REF##*release/}"
          elif [[ $GITHUB_REF = v* ]]; then
            scripts/check-version-is.sh "${GITHUB_REF#v}"
          else
            scripts/check-version-is.sh
          fi
      - run: make test
      - run: |-
          if ! scripts/publish-to.sh $(scripts/gh-semver.sh) $(./scripts/gh-deploy-tag.sh); then
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} scripts/gh-check.sh "NPM Deploy" "failure"
          else
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} scripts/gh-check.sh "NPM Deploy" "success"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
